import sqlite3
import argparse
import os
import sys

def export_cookies(profile_path, domain_substring, out_path):
    db = os.path.join(profile_path, "cookies.sqlite")
    if not os.path.exists(db):
        print("cookies.sqlite not found at", db, file=sys.stderr)
        sys.exit(1)
    con = sqlite3.connect(db)
    cur = con.cursor()
    # host, name, value, path, expiry, isSecure
    cur.execute(
        "SELECT host, name, value, path, expiry, isSecure FROM moz_cookies WHERE host LIKE ?",
        (f"%{domain_substring}%",),
    )
    rows = cur.fetchall()
    if not rows:
        print("No cookies found for domain:", domain_substring, file=sys.stderr)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by export_firefox_cookies.py\n")
        for host, name, value, path, expiry, isSecure in rows:
            flag = "TRUE" if host.startswith(".") else "FALSE"
            secure = "TRUE" if isSecure else "FALSE"
            # Netscape format: domain\tflag\tpath\tsecure\texpiration\tname\tvalue
            f.write(f"{host}\t{flag}\t{path}\t{secure}\t{int(expiry)}\t{name}\t{value}\n")
    con.close()
    print("Wrote", out_path)

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--profile-path", required=True, help="Firefox profile dir (folder containing cookies.sqlite)")
    p.add_argument("--domain", default="kick.com", help="domain substring to export (default: kick.com)")
    p.add_argument("--out", default="cookies.txt", help="output cookies.txt path")
    args = p.parse_args()
    export_cookies(args.profile_path, args.domain, args.out)

if __name__ == "__main__":
    main()